// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `fileInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __fileInterface_h__
#define __fileInterface_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Blond
{

class FileInterface;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Blond::FileInterface>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Blond::FileInterface*);

}

}

namespace Blond
{

class FileInterface;
bool operator==(const FileInterface&, const FileInterface&);
bool operator<(const FileInterface&, const FileInterface&);
::Ice::Object* upCast(::Blond::FileInterface*);
typedef ::IceInternal::Handle< ::Blond::FileInterface> FileInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Blond::FileInterface> FileInterfacePrx;
void __patch(FileInterfacePtr&, const ::Ice::ObjectPtr&);

}

namespace Blond
{

typedef ::std::vector< ::std::string> Files;

}

namespace Blond
{

class Callback_FileInterface_downloadfile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FileInterface_downloadfile_Base> Callback_FileInterface_downloadfilePtr;

class Callback_FileInterface_getfiles_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FileInterface_getfiles_Base> Callback_FileInterface_getfilesPtr;

class Callback_FileInterface_uploadfile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_FileInterface_uploadfile_Base> Callback_FileInterface_uploadfilePtr;

}

namespace IceProxy
{

namespace Blond
{

class FileInterface : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string downloadfile(const ::std::string& file)
    {
        return downloadfile(file, 0);
    }
    ::std::string downloadfile(const ::std::string& file, const ::Ice::Context& __ctx)
    {
        return downloadfile(file, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_downloadfile(const ::std::string& file, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_downloadfile(file, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_downloadfile(const ::std::string& file, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_downloadfile(file, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_downloadfile(const ::std::string& file, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_downloadfile(file, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_downloadfile(const ::std::string& file, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_downloadfile(file, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_downloadfile(const ::std::string& file, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_downloadfile(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_downloadfile(file, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file)
    {
        return begin_downloadfile(file, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file, const ::Ice::Context& __ctx)
    {
        return begin_downloadfile(file, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_downloadfile(file, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_downloadfile(file, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file, const ::Blond::Callback_FileInterface_downloadfilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_downloadfile(file, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string& file, const ::Ice::Context& __ctx, const ::Blond::Callback_FileInterface_downloadfilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_downloadfile(file, &__ctx, __del, __cookie);
    }

    ::std::string end_downloadfile(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string downloadfile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_downloadfile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Blond::Files getfiles()
    {
        return getfiles(0);
    }
    ::Blond::Files getfiles(const ::Ice::Context& __ctx)
    {
        return getfiles(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getfiles(const ::IceInternal::Function<void (const ::Blond::Files&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getfiles(0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getfiles(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getfiles(0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getfiles(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Blond::Files&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getfiles(&ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getfiles(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getfiles(&ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getfiles(const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::Blond::Files&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Blond::Files&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
                ::Blond::Files __ret;
                try
                {
                    __ret = __proxy->end_getfiles(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Blond::Files&)> _response;
        };
        return begin_getfiles(ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getfiles()
    {
        return begin_getfiles(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getfiles(const ::Ice::Context& __ctx)
    {
        return begin_getfiles(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getfiles(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getfiles(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getfiles(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getfiles(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getfiles(const ::Blond::Callback_FileInterface_getfilesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getfiles(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getfiles(const ::Ice::Context& __ctx, const ::Blond::Callback_FileInterface_getfilesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getfiles(&__ctx, __del, __cookie);
    }

    ::Blond::Files end_getfiles(const ::Ice::AsyncResultPtr&);
    
private:

    ::Blond::Files getfiles(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getfiles(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void uploadfile(const ::std::string& file)
    {
        uploadfile(file, 0);
    }
    void uploadfile(const ::std::string& file, const ::Ice::Context& __ctx)
    {
        uploadfile(file, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_uploadfile(const ::std::string& file, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_uploadfile(file, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent));
    }
    ::Ice::AsyncResultPtr
    begin_uploadfile(const ::std::string& file, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_uploadfile(file, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_uploadfile(const ::std::string& file, const ::Ice::Context& ctx, const ::IceInternal::Function<void ()>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_uploadfile(file, &ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(response, exception, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_uploadfile(const ::std::string& file, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_uploadfile(file, &ctx, ::Ice::newCallback(completed, sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file)
    {
        return begin_uploadfile(file, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file, const ::Ice::Context& __ctx)
    {
        return begin_uploadfile(file, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_uploadfile(file, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_uploadfile(file, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file, const ::Blond::Callback_FileInterface_uploadfilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_uploadfile(file, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string& file, const ::Ice::Context& __ctx, const ::Blond::Callback_FileInterface_uploadfilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_uploadfile(file, &__ctx, __del, __cookie);
    }

    void end_uploadfile(const ::Ice::AsyncResultPtr&);
    
private:

    void uploadfile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_uploadfile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<FileInterface> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_secure(bool __secure) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_twoway() const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_oneway() const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_batchOneway() const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_datagram() const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_batchDatagram() const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_compress(bool __compress) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_timeout(int __timeout) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<FileInterface> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<FileInterface*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Blond
{

class FileInterface : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::std::string downloadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Blond::Files getfiles(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void uploadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Blond
{

class FileInterface : virtual public ::IceDelegate::Blond::FileInterface,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::std::string downloadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Blond::Files getfiles(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void uploadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Blond
{

class FileInterface : virtual public ::IceDelegate::Blond::FileInterface,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::std::string downloadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Blond::Files getfiles(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void uploadfile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Blond
{

class FileInterface : virtual public ::Ice::Object
{
public:

    typedef FileInterfacePrx ProxyType;
    typedef FileInterfacePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string downloadfile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___downloadfile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Blond::Files getfiles(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getfiles(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void uploadfile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___uploadfile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const FileInterface& l, const FileInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const FileInterface& l, const FileInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Blond
{

template<class T>
class CallbackNC_FileInterface_downloadfile : public Callback_FileInterface_downloadfile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_FileInterface_downloadfile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_downloadfile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_FileInterface_downloadfilePtr
newCallback_FileInterface_downloadfile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_downloadfile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileInterface_downloadfilePtr
newCallback_FileInterface_downloadfile(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_downloadfile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_FileInterface_downloadfile : public Callback_FileInterface_downloadfile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_FileInterface_downloadfile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_downloadfile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_FileInterface_downloadfilePtr
newCallback_FileInterface_downloadfile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_downloadfile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileInterface_downloadfilePtr
newCallback_FileInterface_downloadfile(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_downloadfile<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_FileInterface_getfiles : public Callback_FileInterface_getfiles_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Blond::Files&);

    CallbackNC_FileInterface_getfiles(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
        ::Blond::Files __ret;
        try
        {
            __ret = __proxy->end_getfiles(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_FileInterface_getfilesPtr
newCallback_FileInterface_getfiles(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Blond::Files&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_getfiles<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileInterface_getfilesPtr
newCallback_FileInterface_getfiles(T* instance, void (T::*cb)(const ::Blond::Files&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_getfiles<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_FileInterface_getfiles : public Callback_FileInterface_getfiles_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Blond::Files&, const CT&);

    Callback_FileInterface_getfiles(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::FileInterfacePrx __proxy = ::Blond::FileInterfacePrx::uncheckedCast(__result->getProxy());
        ::Blond::Files __ret;
        try
        {
            __ret = __proxy->end_getfiles(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_FileInterface_getfilesPtr
newCallback_FileInterface_getfiles(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Blond::Files&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_getfiles<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileInterface_getfilesPtr
newCallback_FileInterface_getfiles(T* instance, void (T::*cb)(const ::Blond::Files&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_getfiles<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_FileInterface_uploadfile : public Callback_FileInterface_uploadfile_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_FileInterface_uploadfile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_uploadfile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_uploadfile<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_uploadfile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_FileInterface_uploadfile<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_FileInterface_uploadfile : public Callback_FileInterface_uploadfile_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_FileInterface_uploadfile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_uploadfile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_uploadfile<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_uploadfile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_FileInterface_uploadfilePtr
newCallback_FileInterface_uploadfile(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_FileInterface_uploadfile<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
