// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `configureServerInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __configureServerInterface_h__
#define __configureServerInterface_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Blond
{

class ConfigureServerInterface;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Blond::ConfigureServerInterface>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Blond::ConfigureServerInterface*);

}

}

namespace Blond
{

class ConfigureServerInterface;
bool operator==(const ConfigureServerInterface&, const ConfigureServerInterface&);
bool operator<(const ConfigureServerInterface&, const ConfigureServerInterface&);
::Ice::Object* upCast(::Blond::ConfigureServerInterface*);
typedef ::IceInternal::Handle< ::Blond::ConfigureServerInterface> ConfigureServerInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Blond::ConfigureServerInterface> ConfigureServerInterfacePrx;
void __patch(ConfigureServerInterfacePtr&, const ::Ice::ObjectPtr&);

}

namespace Blond
{

class Callback_ConfigureServerInterface_getkey_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ConfigureServerInterface_getkey_Base> Callback_ConfigureServerInterface_getkeyPtr;

class Callback_ConfigureServerInterface_setkey_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ConfigureServerInterface_setkey_Base> Callback_ConfigureServerInterface_setkeyPtr;

}

namespace IceProxy
{

namespace Blond
{

class ConfigureServerInterface : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string getkey()
    {
        return getkey(0);
    }
    ::std::string getkey(const ::Ice::Context& __ctx)
    {
        return getkey(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getkey(const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getkey(0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getkey(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getkey(0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getkey(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getkey(&ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getkey(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getkey(&ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getkey(const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_getkey(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_getkey(ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getkey()
    {
        return begin_getkey(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getkey(const ::Ice::Context& __ctx)
    {
        return begin_getkey(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getkey(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getkey(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getkey(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getkey(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getkey(const ::Blond::Callback_ConfigureServerInterface_getkeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getkey(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getkey(const ::Ice::Context& __ctx, const ::Blond::Callback_ConfigureServerInterface_getkeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getkey(&__ctx, __del, __cookie);
    }

    ::std::string end_getkey(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string getkey(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getkey(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int setkey(const ::std::string& key)
    {
        return setkey(key, 0);
    }
    ::Ice::Int setkey(const ::std::string& key, const ::Ice::Context& __ctx)
    {
        return setkey(key, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setkey(const ::std::string& key, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_setkey(key, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_setkey(const ::std::string& key, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setkey(key, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setkey(const ::std::string& key, const ::Ice::Context& ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_setkey(key, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_setkey(const ::std::string& key, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setkey(key, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_setkey(const ::std::string& key, const ::Ice::Context* ctx, const ::IceInternal::Function<void (::Ice::Int)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_setkey(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_setkey(key, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key)
    {
        return begin_setkey(key, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key, const ::Ice::Context& __ctx)
    {
        return begin_setkey(key, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setkey(key, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setkey(key, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key, const ::Blond::Callback_ConfigureServerInterface_setkeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setkey(key, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setkey(const ::std::string& key, const ::Ice::Context& __ctx, const ::Blond::Callback_ConfigureServerInterface_setkeyPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setkey(key, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_setkey(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int setkey(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setkey(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_secure(bool __secure) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_twoway() const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_oneway() const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_batchOneway() const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_datagram() const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_batchDatagram() const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_compress(bool __compress) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ConfigureServerInterface> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ConfigureServerInterface*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Blond
{

class ConfigureServerInterface : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::std::string getkey(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int setkey(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Blond
{

class ConfigureServerInterface : virtual public ::IceDelegate::Blond::ConfigureServerInterface,
                                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::std::string getkey(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int setkey(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Blond
{

class ConfigureServerInterface : virtual public ::IceDelegate::Blond::ConfigureServerInterface,
                                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::std::string getkey(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int setkey(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Blond
{

class ConfigureServerInterface : virtual public ::Ice::Object
{
public:

    typedef ConfigureServerInterfacePrx ProxyType;
    typedef ConfigureServerInterfacePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string getkey(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getkey(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int setkey(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setkey(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const ConfigureServerInterface& l, const ConfigureServerInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ConfigureServerInterface& l, const ConfigureServerInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Blond
{

template<class T>
class CallbackNC_ConfigureServerInterface_getkey : public Callback_ConfigureServerInterface_getkey_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_ConfigureServerInterface_getkey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getkey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_ConfigureServerInterface_getkeyPtr
newCallback_ConfigureServerInterface_getkey(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ConfigureServerInterface_getkey<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ConfigureServerInterface_getkeyPtr
newCallback_ConfigureServerInterface_getkey(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ConfigureServerInterface_getkey<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ConfigureServerInterface_getkey : public Callback_ConfigureServerInterface_getkey_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_ConfigureServerInterface_getkey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getkey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ConfigureServerInterface_getkeyPtr
newCallback_ConfigureServerInterface_getkey(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ConfigureServerInterface_getkey<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ConfigureServerInterface_getkeyPtr
newCallback_ConfigureServerInterface_getkey(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ConfigureServerInterface_getkey<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_ConfigureServerInterface_setkey : public Callback_ConfigureServerInterface_setkey_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_ConfigureServerInterface_setkey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_setkey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_ConfigureServerInterface_setkeyPtr
newCallback_ConfigureServerInterface_setkey(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ConfigureServerInterface_setkey<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ConfigureServerInterface_setkeyPtr
newCallback_ConfigureServerInterface_setkey(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ConfigureServerInterface_setkey<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ConfigureServerInterface_setkey : public Callback_ConfigureServerInterface_setkey_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_ConfigureServerInterface_setkey(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Blond::ConfigureServerInterfacePrx __proxy = ::Blond::ConfigureServerInterfacePrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_setkey(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_ConfigureServerInterface_setkeyPtr
newCallback_ConfigureServerInterface_setkey(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ConfigureServerInterface_setkey<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ConfigureServerInterface_setkeyPtr
newCallback_ConfigureServerInterface_setkey(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ConfigureServerInterface_setkey<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
