// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `sample.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __sample_h__
#define __sample_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Sample
{

class Test;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Sample::Test>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Sample::Test*);

}

}

namespace Sample
{

class Test;
bool operator==(const Test&, const Test&);
bool operator<(const Test&, const Test&);
::Ice::Object* upCast(::Sample::Test*);
typedef ::IceInternal::Handle< ::Sample::Test> TestPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Sample::Test> TestPrx;
void __patch(TestPtr&, const ::Ice::ObjectPtr&);

}

namespace Sample
{

class Callback_Test_getStudent_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Test_getStudent_Base> Callback_Test_getStudentPtr;

}

namespace IceProxy
{

namespace Sample
{

class Test : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int getStudent(::Ice::Int id, ::std::string& name)
    {
        return getStudent(id, name, 0);
    }
    ::Ice::Int getStudent(::Ice::Int id, ::std::string& name, const ::Ice::Context& __ctx)
    {
        return getStudent(id, name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getStudent(::Ice::Int id, const ::IceInternal::Function<void (::Ice::Int, const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStudent(id, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStudent(::Ice::Int id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStudent(id, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getStudent(::Ice::Int id, const ::Ice::Context& ctx, const ::IceInternal::Function<void (::Ice::Int, const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStudent(id, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStudent(::Ice::Int id, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStudent(id, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getStudent(::Ice::Int id, const ::Ice::Context* ctx, const ::IceInternal::Function<void (::Ice::Int, const ::std::string&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int, const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Sample::TestPrx __proxy = ::Sample::TestPrx::uncheckedCast(__result->getProxy());
                ::std::string name;
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_getStudent(name, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret, name);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int, const ::std::string&)> _response;
        };
        return begin_getStudent(id, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id)
    {
        return begin_getStudent(id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id, const ::Ice::Context& __ctx)
    {
        return begin_getStudent(id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStudent(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStudent(id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id, const ::Sample::Callback_Test_getStudentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStudent(id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int id, const ::Ice::Context& __ctx, const ::Sample::Callback_Test_getStudentPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStudent(id, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_getStudent(::std::string& name, const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int getStudent(::Ice::Int, ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getStudent(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Test> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_secure(bool __secure) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_twoway() const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_oneway() const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_batchOneway() const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_datagram() const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_batchDatagram() const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_compress(bool __compress) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Test> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Test*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Sample
{

class Test : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Int getStudent(::Ice::Int, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Sample
{

class Test : virtual public ::IceDelegate::Sample::Test,
             virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Int getStudent(::Ice::Int, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Sample
{

class Test : virtual public ::IceDelegate::Sample::Test,
             virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Int getStudent(::Ice::Int, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Sample
{

class Test : virtual public ::Ice::Object
{
public:

    typedef TestPrx ProxyType;
    typedef TestPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int getStudent(::Ice::Int, ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getStudent(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Test& l, const Test& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Test& l, const Test& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Sample
{

template<class T>
class CallbackNC_Test_getStudent : public Callback_Test_getStudent_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int, const ::std::string&);

    CallbackNC_Test_getStudent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Sample::TestPrx __proxy = ::Sample::TestPrx::uncheckedCast(__result->getProxy());
        ::std::string name;
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getStudent(name, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, name);
        }
    }

    Response response;
};

template<class T> Callback_Test_getStudentPtr
newCallback_Test_getStudent(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Test_getStudent<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Test_getStudentPtr
newCallback_Test_getStudent(T* instance, void (T::*cb)(::Ice::Int, const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Test_getStudent<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Test_getStudent : public Callback_Test_getStudent_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const ::std::string&, const CT&);

    Callback_Test_getStudent(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Sample::TestPrx __proxy = ::Sample::TestPrx::uncheckedCast(__result->getProxy());
        ::std::string name;
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getStudent(name, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, name, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Test_getStudentPtr
newCallback_Test_getStudent(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Test_getStudent<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Test_getStudentPtr
newCallback_Test_getStudent(T* instance, void (T::*cb)(::Ice::Int, const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Test_getStudent<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
